### PR TITLE
Object Factory for Pandora objects extension

### PR DESCRIPTION
**Pull request by rete**
Simple test for a pull request. I just added some spaces in PandoraApi.cc after includes. You can reject it. Is the pull request working ?

### CODE REVIEW

**Comment by johnmarshall80** [comment]
Hi Remi,

This all looks to be working just fine. I can see your modification and (if I wanted to) I could merge it into a branch in my local repository.

Thanks,

John

**Comment by rete** [comment]
Here a first implementation of a Create function in PandoraApi only for CaloHit

**Comment by johnmarshall80** [comment]
Hi Remi,

I've just looked through your changes. I think that they look to be pretty good. It would be great if you have time to extend this templated approach to also cover creation of the other Pandora objects (Tracks, Clusters, Vertices, ParticleFlowObjects).

If you don't have time, I should still be able to pick this up and continue after Easter. If you do manage to get this working for all objects in our Event Data Model, I will then merge it in, make my own modifications (if necessary), then get this into our main repositories for you.

Some quick thoughts:

i). Object creation is possible not just via the PandoraAPIs, but also in algorithms, via the PandoraContentAPIs. Object creation in algorithms includes all input objects (CaloHits, Tracks), and also algorithm objects (Clusters, Vertices, Pfos). The PandoraContentAPIs return the address of the newly constructed object by reference. The new functionality must also be added to the PandoraContentAPI.

ii). It's great to keep backwards-compatibility by having APIs with and without a factory argument. It would help to keep things clean, however, if these options share code in the (hidden) implementation. Somewhere (possibly in the PandoraAPIImpl?), we would drop-in the default factory (i.e. what you get at the moment) for users who did not specify a factory in their API call. Then all manager code remains more-or-less unchanged, except that the actual instantiation is peformed by the provided reference to a factory.

iii). The option to specify a factory probably also needs to be added to the Fragment and MergeFragments APIs. The other option is for each CaloHit to understand which factory it was created by, but I am against this (we must be very careful with our CaloHit memory footprint, as there as so very many hits in e.g. LAr TPC events).

Thanks for your time working on this!

John

**Comment by rete** [comment]
Hi John,

From your last comment, is there a need to specify a factory for the reclustering (InitializeReclustering(...) and EndReclustering(...) ) and the cluster fragmentation (InitializeFragmentation(...) and EndFragmentation(...) ) ? 
I didn't see any call of CaloHit allocation in the (hidden) implementation for these functions but I wanted to be sure before to write anything more.

Rémi

**Comment by johnmarshall80** [comment]
Hi Rémi,

There's no need to provide factories for Reclustering or Fragmentation as these API calls do not actually make the new objects themselves. Instead they set-up the algorithm environment to allow the user to create new objects (potentially re-using Hits that have already been assigned). The user could then, of course, specify their chosen factory.

I've just been discussing this Pandora object-modification approach with my LAr colleagues and there are a couple of places where we might also want to use the new functionality. This will help free-up some of my time to work on this next week.

Thanks,

John

**Comment by rete** [comment]
I have merged the new functionalities locally. I tested it with the ArborContent library which are using these ones. It compiles, run and show the same results as before.
I close this pull request. If new functionalities are added, I will create an other one or we can simply exchange by mail for new ideas. Thanks a lot for for these new changes in the new version

**Pull request closed without merging**
